application: bru-gtug
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /lib
  static_dir: lib
- url: /.*
  static_files: index.html
  upload: index.html